### ISSUE TITLE
[style]lintチェック、フォーマットの導入

### ISSUE THREAD

**Issue by ryota0222** [Connecting-Study-Group/tsunagaru-lt#5]
導入予定は以下の通り
- eslint
- prettier

設定はお任せします！
個人的にはコミット時のチェックをしたい派ですが、他の案があればご相談ください！

**Comment by sunadoi** [comment]
@ryota0222 
これやりたいー！assignしちゃってよいですか？

せっかくならeslintのflat config試したい👀
lint設定するならGitHub Actionsでチェックしたいですね
それあれば個人的にはコミット時のチェックなくてもいいですが、必要そうならhusky入れます！

**Comment by code-yy** [comment]
うわ、いいなこれ

**Comment by ryota0222** [comment]
@sunadoi 
ぜひお願いしますー！
GitHub ActionsはPR時を発火タイミングにしますか？？
コミット時のチェックは無しでも全然大丈夫です！！笑

**Comment by sunadoi** [comment]
lintはpush時にしようかと思います！
PR作成時に通ってても、その後の追加コミットで走らないとちゃんとチェックできなさそうなので

**Comment by ryota0222** [comment]
@sunadoi 
なるほど！push時はしたことないので興味めっちゃあります！ぜひお願いしますー！！
